In [1]:
import pandas as pd
import numpy as np
import ast

In [4]:
folder = 'E:\\UIT DATA SCIENCE\\data samples\\'

In [5]:
df_train = pd.read_csv(folder + 'clip_data\\' + 'final_train_eng_combined.csv')
df_train

Unnamed: 0.1  Unnamed: 0     id  \
0                 0           0      0   
1                 1           1      1   
2                 2           2      2   
3                 3           3      3   
4                 4           4      4   
...             ...         ...    ...   
10800         10800       10800  10800   
10801         10801       10801  10801   
10802         10802       10802  10802   
10803         10803       10803  10803   
10804         10804       10804  10804   

                                        caption_features        sarcasm  \
0      tensor([[ 8.7540e-02, -8.4067e-03, -5.7961e-01...  multi-sarcasm   
1      tensor([[-1.4093e-01,  2.6814e-01,  6.6393e-02...    not-sarcasm   
2      tensor([[ 2.9297e-02,  7.8513e-02,  1.9056e-02...  multi-sarcasm   
3      tensor([[-3.0913e-02, -1.4959e-01, -3.3085e-01...    not-sarcasm   
4      tensor([[-7.7441e-02,  1.9496e-01, -3.8529e-01...  multi-sarcasm   
...                                                  ...            ...   
10800  tensor([[ 1.9143e-01, -8.0573e-02, -5.2628e-01...    not-sarcasm   
10801  tensor([[-2.2732e-01, -9.4946e-02, -6.8110e-02...    not-sarcasm   
10802  tensor([[ 1.4880e-01, -2.0419e-01,  2.2676e-01...    not-sarcasm   
10803  tensor([[ 1.6488e-01,  2.4950e-01, -2.8213e-02...    not-sarcasm   
10804  tensor([[ 4.7611e-02,  1.0246e-01, -1.4754e-01...    not-sarcasm   

                                            image_vector  \
0      tensor([[ 7.2288e-01,  1.0506e-02, -7.5529e-02...   
1      tensor([[ 2.4603e-02,  7.0014e-01,  2.0763e-01...   
2      tensor([[ 2.8290e-01,  1.8930e-01, -7.7651e-02...   
3      tensor([[-1.8501e-02, -1.9456e-01,  3.0173e-02...   
4      tensor([[ 9.5810e-02, -2.5979e-01,  6.2205e-02...   
...                                                  ...   
10800  tensor([[-3.1771e-01,  1.8235e-01,  9.2051e-02...   
10801  tensor([[-2.5732e-01, -8.0080e-02, -2.0398e-01...   
10802  tensor([[-3.1760e-01,  5.6511e-01, -8.7909e-02...   
10803  tensor([[-3.9500e-01,  5.8485e-01, -2.0037e-02...   
10804  tensor([[-2.1180e-01,  2.6338e-02, -4.7125e-01...   

                                              image_text  \
0      tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0...   
1      tensor([[-2.9716e-01,  3.0908e-01, -1.9151e-01...   
2      tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0...   
3      tensor([[ 1.0203e-01,  7.4040e-03, -3.2376e-01...   
4      tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0...   
...                                                  ...   
10800  tensor([[-1.3304e-01, -1.4935e-01, -2.7408e-01...   
10801  tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0...   
10802  tensor([[-6.1615e-02,  1.7048e-01, -1.7485e-01...   
10803  tensor([[ 4.2279e-01,  1.5298e-01, -1.2523e-01...   
10804  tensor([[ 4.5899e-01, -4.0766e-01, -1.7532e-01...   

                                                  object  \
0      tensor([[ 2.4169e-01,  7.7020e-02, -1.2376e-02...   
1      tensor([[ 2.8199e-01, -1.5914e-01, -1.4282e-01...   
2      tensor([[ 1.9386e-01,  1.0891e-01,  1.7538e-01...   
3      tensor([[ 3.0898e-01,  2.0793e-01, -4.3984e-01...   
4      tensor([[-1.4243e-03,  1.6136e-01, -3.6162e-01...   
...                                                  ...   
10800  tensor([[ 2.8199e-01, -1.5914e-01, -1.4282e-01...   
10801  tensor([[ 3.7033e-01,  1.1122e-01,  1.4711e-02...   
10802  tensor([[-6.7110e-02,  1.9595e-01, -3.0825e-01...   
10803  tensor([[ 2.8199e-01, -1.5914e-01, -1.4282e-01...   
10804  tensor([[ 2.4169e-01,  7.7020e-02, -1.2376e-02...   

                                             description  
0      tensor([[ 1.4588e-01, -1.4534e-02, -3.4795e-01...  
1      tensor([[-5.6289e-02,  4.7537e-01, -6.9459e-02...  
2      tensor([[ 3.7038e-01,  3.1744e-01, -1.2233e-01...  
3      tensor([[-3.3589e-01,  9.8876e-02, -1.0965e-01...  
4      tensor([[ 3.1547e-01, -1.3707e-01, -2.7851e-01...  
...                                                  ...  
10800  tensor([[-6.3018e-

In [ ]:
df_public = pd.read_csv(folder + 'clip_data\\' + 'final_dev_public_eng_combined.csv')
df_public

In [5]:
def string_to_tensor_array(string_data):
    # Chuyển đổi chuỗi chứa tensor thành mảng NumPy
    # Loại bỏ 'tensor(' và ')', và sử dụng ast.literal_eval để chuyển đổi
    array_data = ast.literal_eval(string_data.replace('tensor(', '').replace(')', ''))
    return np.array(array_data)

def tranforms(data):
    # Chuyển đổi cột image và text thành NumPy arrays
    data['image_vector'] = data['image_vector'].apply(string_to_tensor_array)
    data['caption_features'] = data['caption_features'].apply(string_to_tensor_array)
    data['image_text'] = data['image_text'].apply(string_to_tensor_array)

    # Chuyển đổi thành NumPy arrays
    res_images = np.array(data['image_vector'].tolist())
    res_texts = np.array(data['caption_features'].tolist())
    res_image_text = np.array(data['image_text'].tolist())

    return res_images, res_texts, res_image_text

In [ ]:
X_train_images, X_train_texts, X_train_images_text = tranforms(df_train)
y_train = df_train['sarcasm']

In [8]:
X_dev_images, X_dev_texts, X_dev_images_text = tranforms(df_public)

In [62]:
# In ra các giá trị độc nhất trong y_train
print("Các giá trị độc nhất trong y_train:")
print(y_train.unique())

Các giá trị độc nhất trong y_train:
['multi-sarcasm' 'not-sarcasm' 'image-sarcasm' 'text-sarcasm']


In [63]:
label_mapping = {
    'not-sarcasm': 0,
    'multi-sarcasm': 1,
    'image-sarcasm': 2,
    'text-sarcasm': 3
}

In [64]:
y_train = y_train.map(label_mapping)

In [68]:
# Xuất kích thước của các numpy arrays
print("Shape of training images:", X_train_images.shape)
print("Shape of training texts:", X_train_texts.shape)
print("Shape of training images_text:", X_train_images_text.shape)
print("Shape of training labels:", y_train.shape)
# print("Shape of validation images:", val_x_images.shape)
# print("Shape of validation texts:", val_x_texts.shape)
# print("Shape of validation images_text:", val_x_images_text.shape)
# print("Shape of validation texts:", val_y.shape)

Shape of training images: (10805, 1, 768)
Shape of training texts: (10805, 1, 768)
Shape of training images_text: (10805, 1, 768)
Shape of training labels: (10805,)


### __MÔ HÌNH__

In [69]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout, Dense, Input, concatenate
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold
from tensorflow.keras.layers import Layer
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
from sklearn.utils.class_weight import compute_class_weight
from sklearn.utils import resample

def prepare_data_with_oversampling(X_images, X_texts, X_images_text, y):
    # Over-sampling với các mẫu ít nhất (text-sarcasm)
    data = list(zip(X_images, X_texts, X_images_text, y))
    data_df = pd.DataFrame(data, columns=['images', 'texts', 'images_text', 'labels'])

    # Tách riêng các nhóm theo nhãn
    max_label_count = data_df['labels'].value_counts().max()
    sampled_data = []
    for label in data_df['labels'].unique():
        label_data = data_df[data_df['labels'] == label]
        # Nếu nhãn ít hơn max_label_count, thực hiện Over-sampling
        if len(label_data) < max_label_count:
            label_data = resample(label_data, replace=True, n_samples=max_label_count, random_state=42)
        sampled_data.append(label_data)
    
    # Kết hợp lại các mẫu
    balanced_data = pd.concat(sampled_data)

    # Tách dữ liệu đã over-sampling
    X_images_balanced = np.stack(balanced_data['images'].values)
    X_texts_balanced = np.stack(balanced_data['texts'].values)
    X_images_text_balanced = np.stack(balanced_data['images_text'].values)
    y_balanced = np.array(balanced_data['labels'].values)
    
    return X_images_balanced, X_texts_balanced, X_images_text_balanced, y_balanced

def get_class_weights(y):
    classes = np.unique(y)
    class_weights = compute_class_weight('balanced', classes=classes, y=y)
    class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}
    return class_weights_dict

# Custom Self-Attention Layer (unchanged)
class SelfAttention(Layer):
    def __init__(self, **kwargs):
        super(SelfAttention, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1]), initializer="glorot_uniform", trainable=True)
        self.b = self.add_weight(shape=(input_shape[-1],), initializer="zeros", trainable=True)
        self.u = self.add_weight(shape=(input_shape[-1],), initializer="glorot_uniform", trainable=True)

    def call(self, inputs):
        score = tf.tanh(tf.tensordot(inputs, self.W, axes=[-1, 0]) + self.b)
        attention_weights = tf.tensordot(score, self.u, axes=[-1, 0])
        attention_weights = tf.nn.softmax(attention_weights, axis=1)
        context_vector = attention_weights[..., tf.newaxis] * inputs
        context_vector = tf.reduce_sum(context_vector, axis=1)
        return context_vector

    def get_config(self):
        config = super(SelfAttention, self).get_config()
        return config

    @classmethod
    def from_config(cls, config):
        return cls(**config)

# Custom callback để tính F1-macro sau mỗi epoch và lưu mô hình tốt nhất (unchanged)
class F1MacroCallback(tf.keras.callbacks.Callback):
    def __init__(self, validation_data, save_path):
        super(F1MacroCallback, self).__init__()
        self.validation_data = validation_data
        self.best_f1 = 0.0  # F1-macro tốt nhất
        self.save_path = save_path

    def on_epoch_end(self, epoch, logs=None):
        X_val, y_val = self.validation_data
        y_pred = self.model.predict(X_val)
        y_pred_labels = np.argmax(y_pred, axis=1)
        f1 = f1_score(y_val, y_pred_labels, average='macro')
        logs['val_f1_macro'] = f1
        print(f' - val_f1_macro: {f1:.4f}')
        if f1 > self.best_f1:
            self.best_f1 = f1
            self.model.save(self.save_path)
            print(f'Model saved with val_f1_macro: {f1:.4f}')

# Tạo mô hình CNN với Self-Attention cho hình ảnh và văn bản (unchanged)
def create_model(num_filters=64, filter_size=3, pool_size=1, learning_rate=0.0001):
    input_images = Input(shape=(1, 768))
    x1 = Conv1D(filters=num_filters, kernel_size=filter_size, activation='relu', padding='same')(input_images)
    x1 = MaxPooling1D(pool_size=1)(x1)
    x1 = Dropout(0.5)(x1)
    x1 = SelfAttention()(x1)
    
    input_texts = Input(shape=(1, 768))
    x2 = Conv1D(filters=num_filters, kernel_size=filter_size, activation='relu', padding='same')(input_texts)
    x2 = MaxPooling1D(pool_size=1)(x2)
    x2 = Dropout(0.5)(x2)
    x2 = SelfAttention()(x2)
    
    input_images_text = Input(shape=(1, 768))
    x3 = Conv1D(filters=num_filters, kernel_size=filter_size, activation='relu', padding='same')(input_images_text)
    x3 = MaxPooling1D(pool_size=1)(x3)
    x3 = Dropout(0.5)(x3)
    x3 = SelfAttention()(x3)
    
    combined = concatenate([x1, x2, x3])
    output = Dense(4, activation='softmax')(combined)
    model = Model(inputs=[input_images, input_texts, input_images_text], outputs=output)
    optimizer = Adam(learning_rate=learning_rate)
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

def run_kfold_with_sampling(X_train_images, X_train_texts, X_train_images_text, y_train, n_splits=5):
    kfold = KFold(n_splits=n_splits, shuffle=True)
    fold_no = 1
    all_val_f1 = []

    for train_idx, val_idx in kfold.split(X_train_images):
        print(f'Training fold {fold_no}...')

        # Tạo dữ liệu huấn luyện với over-sampling
        X_train_fold_images, X_train_fold_texts, X_train_fold_images_text, y_train_fold = prepare_data_with_oversampling(
            X_train_images[train_idx], 
            X_train_texts[train_idx], 
            X_train_images_text[train_idx], 
            y_train[train_idx]
        )

        # Chuẩn bị dữ liệu validation
        X_val_fold = [X_train_images[val_idx], X_train_texts[val_idx], X_train_images_text[val_idx]]
        y_val_fold = y_train[val_idx]

        # Tạo mô hình mới cho mỗi fold
        model = create_model()

        # Đường dẫn lưu mô hình tốt nhất của mỗi fold
        checkpoint_filepath = f'best_model_fold_{fold_no}.keras'

        # Tính toán class weights
        class_weights = get_class_weights(y_train_fold)

        # Callback F1-macro để lưu mô hình tốt nhất
        f1_macro_callback = F1MacroCallback(validation_data=(X_val_fold, y_val_fold), save_path=checkpoint_filepath)

        # Huấn luyện mô hình với class weights và callback
        history = model.fit(
            [X_train_fold_images, X_train_fold_texts, X_train_fold_images_text], 
            y_train_fold, 
            epochs=40, 
            validation_data=(X_val_fold, y_val_fold),
            class_weight=class_weights,  # Weighted Loss
            callbacks=[f1_macro_callback]
        )

        # Đánh giá mô hình tốt nhất trên tập validation
        best_model = tf.keras.models.load_model(checkpoint_filepath, custom_objects={'SelfAttention': SelfAttention})

        # Tính F1-macro trên tập validation của mô hình tốt nhất
        y_pred = best_model.predict(X_val_fold)
        y_pred_labels = np.argmax(y_pred, axis=1)
        val_f1 = f1_score(y_val_fold, y_pred_labels, average='macro')
        print(f'Best model val_f1_macro for fold {fold_no}: {val_f1*100:.2f}%')

        all_val_f1.append(val_f1)
        fold_no += 1

    print(f'Mean F1-macro across all folds: {np.mean(all_val_f1)*100:.2f}%')

# Thực hiện huấn luyện K-Fold với over-sampling và weighted loss
run_kfold_with_sampling(X_train_images, X_train_texts, X_train_images_text, y_train)

Training fold 1...
Epoch 1/40
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step   - accuracy: 0.5925 
 - val_f1_macro: 0.4067
Model saved with val_f1_macro: 0.4067
601/601 ━━━━━━━━━━━━━━━━━━━━ 29s 28ms/step - accuracy: 0.5927 - loss: 0.9454 - val_accuracy: 0.6553 - val_loss: 0.7626 - val_f1_macro: 0.4067
Epoch 2/40
68/68 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step ep - accuracy: 0.79
 - val_f1_macro: 0.4148
Model saved with val_f1_macro: 0.4148
601/601 ━━━━━━━━━━━━━━━━━━━━ 18s 30ms/step - accuracy: 0.7936 - loss: 0.5200 - val_accuracy: 0.6432 - val_loss: 0.7830 - val_f1_macro: 0.4148
Epoch 3/40
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step ep - accuracy: 0.8470 -
 - val_f1_macro: 0.4141
601/601 ━━━━━━━━━━━━━━━━━━━━ 15s 21ms/step - accuracy: 0.8470 - loss: 0.3956 - val_accuracy: 0.6548 - val_loss: 0.7672 - val_f1_macro: 0.4141
Epoch 4/40
68/68 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step ep - accuracy: 0.8659 -
 - val_f1_macro: 0.4229
Model saved with val_f1_macro: 0.4229
601/601 ━━━━━━━━━━━━━━━━━━━━ 15s 25ms/step - accuracy:

In [33]:
from tensorflow.keras.models import load_model
import tensorflow as tf

# Đọc mô hình đã lưu từ file
best_model = tf.keras.models.load_model('E:\\best_k_fold_f1_macro\\best_model_fold_1_4331.keras', custom_objects={'SelfAttention': SelfAttention})
# Đánh giá mô hình trên tập dữ liệu test hoặc validation
# Giả sử bạn có dữ liệu test: X_test_images, X_test_texts, X_test_images_text, y_test
# test_loss, test_accuracy = best_model.evaluate([X_train_images, X_train_texts, X_train_images_text], y_train)
# print(f'Test accuracy: {test_accuracy*100:.2f}%')

# Sử dụng mô hình để dự đoán
# Giả sử bạn có dữ liệu mới: X_new_images, X_new_texts, X_new_images_text
predictions = best_model.predict([X_dev_images, X_dev_texts, X_dev_images_text])

# In ra kết quả dự đoán
print(predictions)

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['input_layer_3', 'input_layer_4', 'input_layer_5']. Received: the structure of inputs=('*', '*', '*')
  warnings.warn(


45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
[[4.7113471e-02 8.6384475e-01 8.6392276e-02 2.6495077e-03]
 [2.7035898e-01 6.8785483e-01 3.9151393e-02 2.6347442e-03]
 [9.4934094e-01 4.2644002e-02 4.8829406e-03 3.1321631e-03]
 ...
 [2.5127545e-01 7.1528524e-01 3.0758295e-02 2.6809794e-03]
 [2.3068228e-01 7.2391027e-01 4.4426341e-02 9.8110281e-04]
 [6.8013430e-02 8.4772366e-01 8.3442032e-02 8.2085829e-04]]


In [34]:
# Chuyển predictions về dạng nhãn bằng np.argmax
predicted_labels = np.argmax(predictions, axis=1)

# Mapping các chỉ số thành nhãn
label_mapping = {
    0: 'not-sarcasm',
    1: 'multi-sarcasm',
    2: 'image-sarcasm',
    3: 'text-sarcasm'
}

# Chuyển đổi predicted_labels thành nhãn từ label_mapping
predicted_label_names = [label_mapping[label] for label in predicted_labels]

# In ra nhãn dự đoán
print("Predicted labels:\n", predicted_label_names)

Predicted labels:
 ['multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'multi-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'not-sarcasm', 'multi-sarcasm', '

In [35]:
list(set(predicted_label_names))

['image-sarcasm', 'multi-sarcasm', 'not-sarcasm']

In [38]:
import json

results = {df_public.index[i]: predicted_label_names[i] for i in range(len(predicted_label_names))}

# Tạo cấu trúc JSON
output = {
    "results": results,
    "phase": "dev"
}

# Chuyển đổi sang chuỗi JSON
json_output = json.dumps(output, indent=4)

# In ra kết quả
print(json_output)

{
    "results": {
        "0": "multi-sarcasm",
        "1": "multi-sarcasm",
        "2": "not-sarcasm",
        "3": "not-sarcasm",
        "4": "not-sarcasm",
        "5": "not-sarcasm",
        "6": "not-sarcasm",
        "7": "not-sarcasm",
        "8": "not-sarcasm",
        "9": "not-sarcasm",
        "10": "multi-sarcasm",
        "11": "multi-sarcasm",
        "12": "not-sarcasm",
        "13": "not-sarcasm",
        "14": "multi-sarcasm",
        "15": "not-sarcasm",
        "16": "not-sarcasm",
        "17": "not-sarcasm",
        "18": "not-sarcasm",
        "19": "not-sarcasm",
        "20": "not-sarcasm",
        "21": "not-sarcasm",
        "22": "not-sarcasm",
        "23": "not-sarcasm",
        "24": "multi-sarcasm",
        "25": "not-sarcasm",
        "26": "not-sarcasm",
        "27": "not-sarcasm",
        "28": "not-sarcasm",
        "29": "not-sarcasm",
        "30": "not-sarcasm",
        "31": "not-sarcasm",
        "32": "multi-sarcasm",
        "33": "multi

In [39]:
with open('results.json', 'w') as json_file:
    json.dump(output, json_file, indent=4)